### ISSUE TITLE
cant find file "args. py"

### ISSUE THREAD

**Issue by Sha-mu** [yudianzheng/SketchVideo#4]
When I was running the fifth step, I found that I needed to find the ”result“ folder under the dataset folder. This folder was generated in the fourth step, but when I ran the fourth step, I found that the "args. py" file was missing. Additionally, some files are missing include。

**Comment by Sha-mu** [comment]
I just want to use my own video to refer to it, but I need to be trained to have a checkpoint, is there a code for referencing?

**Comment by yudianzheng** [comment]
you can use sh scripts/operate_atlas.sh <video_name> to train a checkpoint or you can follow code of "layered-neural-atlases"

**Comment by yudianzheng** [comment]
> you can use sh scripts/operate_atlas.sh <video_name> to train a checkpoint or you can follow code of "layered-neural-atlases"



> I just want to use my own video to inference, but I need to be trained to have a checkpoint, is there a code for inference？

**Comment by yudianzheng** [comment]
> I just want to use my own video to inference, but I need to be trained to have a checkpoint, is there a code for inference？

you can use sh scripts/operate_atlas.sh <video_name> to train a checkpoint or you can follow code of "layered-neural-atlases"
