### ISSUE TITLE
How to reduce the training time?

### ISSUE THREAD

**Issue by YongLD** [yudianzheng/SketchVideo#7]
I found that the training time is too long. Even with my A100, it takes a whole day and night to train. How can I reduce the training time? Should I just lower the iters_num parameter? Does iters_num really need to be 10,001?
Or, can I reduce the training time by importing a pre-trained model?

**Comment by YongLD** [comment]
I’m curious, how long does it take for you to train a single model?

**Comment by YongLD** [comment]
How to use CoDef in this project? Is it enough to just change `layered-neural-atlases` to CoDeF?

**Comment by yudianzheng** [comment]
> How to use CoDef in this project? Is it enough to just change `layered-neural-atlases` to CoDeF?

Sorry, but CoDeF is a new project and has not been adapted to this project yet.

**Comment by YongLD** [comment]
> > I’m curious, how long does it take for you to train a single model?
> 
> The number of iterations does not need to be 10,001. You can reduce the training time by lowering the iteration count for both the NLA model training (which can be skipped if you import a pre-trained model) and the optimization pipeline, as well as by decreasing the number of sketches. Typically, it takes 20-30 minutes to train a NLA model and about 20 minutes to optimize a sketch video. In fact, both the training time and quality can be improved by using a better model like CoDeF, if you want to try it.

Alright, Thank you very much for your generous response！I have two more questions I'd like to ask you. What is an appropriate number of iterations? Can I use the same pre-trained model, or do I need different pre-trained models for different datasets?

**Comment by YongLD** [comment]
After using the pre-trained model and changing the number of iterations to 1500, the checkpoint was not generated. Is the checkpoint only saved after evaluation?

**Comment by yudianzheng** [comment]
> > > I’m curious, how long does it take for you to train a single model?
> > 
> > 
> > The number of iterations does not need to be 10,001. You can reduce the training time by lowering the iteration count for both the NLA model training (which can be skipped if you import a pre-trained model) and the optimization pipeline, as well as by decreasing the number of sketches. Typically, it takes 20-30 minutes to train a NLA model and about 20 minutes to optimize a sketch video. In fact, both the training time and quality can be improved by using a better model like CoDeF, if you want to try it.
> 
> Alright, Thank you very much for your generous response！I have two more questions I'd like to ask you. What is an appropriate number of iterations? Can I use the same pre-trained model, or do I need different pre-trained models for different datasets?

he appropriate number could be between 400 and 700 for a 5-second video (for optimization). For different videos, it is necessary to train a different NLA model.

**Comment by yudianzheng** [comment]
> > > I’m curious, how long does it take for you to train a single model?
> > 
> > 
> > The number of iterations does not need to be 10,001. You can reduce the training time by lowering the iteration count for both the NLA model training (which can be skipped if you import a pre-trained model) and the optimization pipeline, as well as by decreasing the number of sketches. Typically, it takes 20-30 minutes to train a NLA model and about 20 minutes to optimize a sketch video. In fact, both the training time and quality can be improved by using a better model like CoDeF, if you want to try it.
> 
> Alright, Thank you very much for your generous response！I have two more questions I'd like to ask you. What is an appropriate number of iterations? Can I use the same pre-trained model, or do I need different pre-trained models for different datasets?

The appropriate number could be between 400 and 700 for a 5-second video (for optimization). For different videos, it is necessary to train a different NLA model.

**Comment by yudianzheng** [comment]
> After using the pre-trained model and changing the number of iterations to 1500, the checkpoint was not generated. Is the checkpoint only saved after evaluation?

The checkpoint should be saved if the entire process is followed.

**Comment by YongLD** [comment]
This is an excellent piece of work. Thank you for your response!
